# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=200)),
                ('push_token', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRoomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exit', models.BooleanField(default=False)),
                ('is_host', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='kalalarm.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alarm_date', models.IntegerField()),
                ('alarm_time', models.TimeField()),
                ('is_repeat', models.BooleanField(default=False)),
                ('alarm_ring_name', models.CharField(max_length=500, null=True)),
                ('max_device', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='deviceroomlist',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='kalalarm.Room'),
        ),
    ]
